### PR TITLE
Release/4.7

### PR DESCRIPTION
**Pull request by sharwell**

### CODE REVIEW

**Comment by sharwell** [comment]
@danielsun1106 Let me know if you observe any breaking changes with this release. It should be available through Maven in the next couple of hours (after the next sync).

**Comment by danielsun1106** [comment]
Thanks for your hard work, Sam.
I'll test it via the new parser Parrot of Apache Groovy :)

**Comment by danielsun1106** [comment]
Sam, 4.7 does not appear in the maven repository after waiting for about a day.
https://mvnrepository.com/artifact/com.tunnelvisionlabs/antlr4

**Comment by sharwell** [comment]
http://search.maven.org/#artifactdetails%7Ccom.tunnelvisionlabs%7Cantlr4%7C4.7%7Cjar

**Comment by danielsun1106** [comment]
Gotcha :-)

**Comment by danielsun1106** [comment]
Sam, all tests passes after bumped antlr version to 4.7 :-)

https://travis-ci.org/danielsun1106/groovy-parser/builds/262466695
https://travis-ci.org/apache/groovy/builds/262467619

**Pull request merged**
